---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser

- name: enable puma
  systemd: name=puma enabled=yes

- name: Fetch the latest version of application code
  git:
    repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
    dest: /home/appuser/reddit
    version: monolith
  notify: restart puma

- name: Bundle install
  bundler:
    state: present
    chdir: /home/appuser/reddit


